# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bea87071ef0c3cfe624eadc56e142fdf57e05060d4322ff00215ae7c13ce8b99a4e205387badad166be95d73d1e9e40a88b2d680b6b6ce34384587c2e81239e

test:
  secret_key_base: e0edec729ae85806695708471e8f3e8235976c8c059a28c74f5d404a6f5035363ca8f16269fc738ec2cfaac7dbde87379ffe0263956a135976424d93df060649

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
